# -*- coding: utf-8 -*-
"""Prak4_Perkondisian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kd4VvXq-61k_jvXcfE6I2k6FbHD457iP
"""

# Fungsi dasar
def tampil_pesan():
    print("Hello, ini Fungsi!")

# Fungsi salam
def salam():
    print("Hello, Selamat Pagi")

# Pemanggilan fungsi salam beberapa kali
salam()
salam()
salam()

# Fungsi salam dengan parameter
def salam_dengan_pesan(ucapan):
    print(ucapan)

# Contoh pemanggilan fungsi dengan parameter
salam_dengan_pesan("Selamat siang, Firmansyah!")

# Fungsi dasar dengan parameter
def tampil_parameter(parameter):
    print(parameter)

# Menghitung luas segitiga
def hitung_luas_segitiga(alas, tinggi):
    luas = (alas * tinggi) / 2
    print("Luas segitiga: %f" % luas)

# Pemanggilan fungsi luas segitiga
hitung_luas_segitiga(4, 6)

# Menghitung luas persegi
def hitung_luas_persegi(sisi):
    luas = sisi * sisi
    return luas

# Pemanggilan fungsi luas persegi
print("Luas persegi: %d" % hitung_luas_persegi(6))

# Menghitung volume kubus
def hitung_volume_kubus(sisi):
    volume = hitung_luas_persegi(sisi) * sisi
    return volume

# Pemanggilan fungsi volume kubus
print("Volume kubus: %d" % hitung_volume_kubus(3))

# Variabel global
nama = "Firmansyah"
versi = "1.0.0"

def tampil_info_program():
    # Variabel lokal
    nama_program = "Program Firmansyah"
    versi_program = "1.0.2"
    # Menampilkan informasi lokal
    print("Nama Program: %s" % nama_program)
    print("Versi Program: %s" % versi_program)

# Menampilkan informasi global
print("Nama Pengguna: %s" % nama)
print("Versi Aplikasi: %s" % versi)

# Memanggil fungsi tampil_info_program
tampil_info_program()

# Variabel global untuk menyimpan data film
film = []

# Fungsi untuk menampilkan semua data
def tampil_data():
    if len(film) <= 0:
        print("BELUM ADA DATA")
    else:
        for indeks, judul in enumerate(film):
            print("[%d] %s" % (indeks, judul))

# Fungsi untuk menambah data
def tambah_data():
    judul_baru = input("Judul Film: ")
    film.append(judul_baru)

# Fungsi untuk mengedit data
def ubah_data():
    tampil_data()
    try:
        indeks = int(input("Inputkan ID film: "))
        if indeks >= len(film):
            print("ID tidak ditemukan")
        else:
            judul_baru = input("Judul baru: ")
            film[indeks] = judul_baru
    except ValueError:
        print("Input harus berupa angka!")

# Fungsi untuk menghapus data
def hapus_data():
    tampil_data()
    try:
        indeks = int(input("Inputkan ID film: "))
        if indeks >= len(film):
            print("ID tidak ditemukan")
        else:
            film.pop(indeks)
    except ValueError:
        print("Input harus berupa angka!")

# Fungsi untuk menampilkan menu
def tampilkan_menu():
    print("\n----------- MENU ----------")
    print("[1] Tampilkan Data")
    print("[2] Tambah Data")
    print("[3] Ubah Data")
    print("[4] Hapus Data")
    print("[5] Keluar")

    try:
        pilihan = int(input("PILIH MENU> "))
        print("\n")
        if pilihan == 1:
            tampil_data()
        elif pilihan == 2:
            tambah_data()
        elif pilihan == 3:
            ubah_data()
        elif pilihan == 4:
            hapus_data()
        elif pilihan == 5:
            exit()
        else:
            print("Pilihan tidak valid!")
    except ValueError:
        print("Input harus berupa angka!")

# Program utama
if __name__ == "__main__":
    while True:
        tampilkan_menu()